# Generated by Django 3.0.8 on 2020-07-20 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0002_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='choices',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogg.Categories'),
        ),
    ]
